"use strict";
jQuery(window).load(function(){
        
        var custommenuHTML  ='<div class="swpRightPos">';
        custommenuHTML +=    '<a href="#" class="swpRightPosButton">';
        custommenuHTML +=        '<span class="rt-icon-cog2 animate-spin"></span>';
        custommenuHTML +=    '</a>';
        custommenuHTML +=    '<div class="sc_tabs inited ui-tabs ui-widget ui-widget-content ui-corner-all" data-active="0">';
        custommenuHTML +=        '<ul class="nav nav-tabs tabsMenuHead ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">';
        custommenuHTML +=            '<li class="active right_tab_custom ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab" data-toggle="tab">';
        custommenuHTML +=                '<a class="tabsCustom ui-tabs-anchor" href="#tabsCustom" role="tab" data-toggle="tab"></a>';
        custommenuHTML +=            '</li>';
        custommenuHTML +=            '<li class="right_tab_menu ui-state-default ui-corner-top">';
        custommenuHTML +=                '<a class="tabsMenu ui-tabs-anchor" href="#tabsMenu" role="tab" data-toggle="tab"></a>';
        custommenuHTML +=            '</li>';
        custommenuHTML +=            '<li class="right_tab_favorites ui-state-default ui-corner-top">';
        custommenuHTML +=                '<a class="tabsFavorite ui-tabs-anchor" href="#tabsFavorite" role="tab" data-toggle="tab"></a>';
        custommenuHTML +=            '</li>';
        custommenuHTML +=        '</ul>';
        custommenuHTML +=        '<div class="tab-content">';
        custommenuHTML +=            '<div id="tabsCustom" class="tab-pane fade in active tabsMenuBody ui-tabs-panel ui-widget-content ui-corner-bottom" >';
        custommenuHTML +=                '<div id="custom_options">';
        custommenuHTML +=                    '<div id="custom_options_scroll" class="sc_scroll sc_scroll_vertical scroll-container inited custom_options_scroll">';
        custommenuHTML +=                        '<div class="sc_scroll_wrapper">';
        custommenuHTML +=                            '<div class="sc_scroll_slide">';
        custommenuHTML +=                                '<div class="co_header">';
        custommenuHTML +=                                    '<h4 class="co_title">Choose Your Style</h4>';
        custommenuHTML +=                                    '<a href="index.html" class="co_reset_to_default fa fa-refresh" title="Reset to default"></a>';
        custommenuHTML +=                                '</div>';
        custommenuHTML +=                                '<div class="co_options">';
        custommenuHTML +=                                    '<form name="co_form">';
        custommenuHTML +=                                        '<input type="hidden" id="co_site_url" name="co_site_url" value="#">';
        custommenuHTML +=                                        '<div class="co_form_row">';
        custommenuHTML +=                                            '<input type="hidden" name="co_body_style" value="fullscreen">';
        custommenuHTML +=                                            '<span class="co_label">Body style:</span>';
        custommenuHTML +=                                            '<div class="co_switch_box">';
        custommenuHTML +=                                                '<a href="#" class="co_switch_label wide">Wide</a>';
        custommenuHTML +=                                                '<div class="switcher"><a href="#" class="ui-draggable ui-draggable-handle"></a></div>';
        custommenuHTML +=                                                '<a href="#" class="co_switch_label boxed">Boxed</a>';
        custommenuHTML +=                                            '</div>';
        custommenuHTML +=                                        '</div>';
        custommenuHTML +=                                        '<div class="co_form_row">';
        custommenuHTML +=                                            '<span class="co_label">Theme colors:</span>';
        custommenuHTML +=                                            '<div class="co_form_subrow">';
        custommenuHTML +=                                                '<input type="hidden" name="co_theme_color" value="#f55858">';
        custommenuHTML +=                                                '<div id="co_theme_color" class="iColorPicker"></div>';
        custommenuHTML +=                                                '<input type="hidden" name="co_theme_color_1" value="#ffc455">';
        custommenuHTML +=                                                '<div id="co_theme_color_1" class="iColorPicker"></div>';
        custommenuHTML +=                                                '<input type="hidden" name="co_theme_color_2" value="#392071">';
        custommenuHTML +=                                                '<div id="co_theme_color_2" class="iColorPicker"></div>';
        custommenuHTML +=                                                '<input type="hidden" name="co_theme_color_3" value="#05d1d4">';
        custommenuHTML +=                                                '<div id="co_theme_color_3" class="iColorPicker"></div>';
        custommenuHTML +=                                            '</div>';
        custommenuHTML +=                                        '</div>';
        custommenuHTML +=                                        '<div class="co_form_row">';
        custommenuHTML +=                                            '<input type="hidden" name="co_bg_pattern" value="">';
        custommenuHTML +=                                            '<span class="co_label">Theme pattern:</span>';
        custommenuHTML +=                                            '<div id="co_bg_pattern_list">';
        custommenuHTML +=                                                '<a href="#" id="pattern_1" class="co_pattern_wrapper"><img src="img/pattern_1_thumb2.png" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="pattern_2" class="co_pattern_wrapper"><img src="img/pattern_2_thumb2.png" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="pattern_3" class="no_margin co_pattern_wrapper"><img src="img/pattern_3_thumb2.png" alt=""></a>';
        custommenuHTML +=                                            '</div>';
        custommenuHTML +=                                        '</div>';
        custommenuHTML +=                                        '<div class="co_form_row">';
        custommenuHTML +=                                            '<input type="hidden" name="co_bg_image" value="">';
        custommenuHTML +=                                            '<span class="co_label">Backgroud images:</span>';
        custommenuHTML +=                                            '<div id="co_bg_images_list">';
        custommenuHTML +=                                                '<a href="#" id="image_1" class="co_image_wrapper"><img src="img/image_1_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="image_2" class="co_image_wrapper"><img src="img/image_2_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="image_3" class="no_margin co_image_wrapper"><img src="img/image_3_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="image_4" class="co_image_wrapper"><img src="img/image_4_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="image_5" class="co_image_wrapper"><img src="img/image_5_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                                '<a href="#" id="image_6" class="no_margin co_image_wrapper"><img src="img/image_6_thumb2.jpg" alt=""></a>';
        custommenuHTML +=                                            '</div>';
        custommenuHTML +=                                            '<div id="co_bg_images"></div>';
        custommenuHTML +=                                        '</div>';
        custommenuHTML +=                                    '</form>';
        custommenuHTML +=                                '</div>';
        custommenuHTML +=                            '</div>';
        custommenuHTML +=                        '</div>';
        custommenuHTML +=                    '</div>';
        custommenuHTML +=                '</div>';
        custommenuHTML +=            '</div>';
        custommenuHTML +=            '<div id="tabsMenu" class="tab-pane fade tabsMenuBody ui-tabs-panel ui-widget-content ui-corner-bottom" >';
        custommenuHTML +=                '<div class="sc_scroll sc_scroll_vertical scroll-container" id="panelmenu_scroll">';
        custommenuHTML +=                    '<div class="sc_scroll_wrapper">';
        custommenuHTML +=                        '<div class="sc_scroll_slide">';
        custommenuHTML +=                            '<nav role="navigation" class="panelmenu_area widget_area">';
        custommenuHTML +=                                '<ul id="panelmenu" class="">';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item current_page_item menu-item-has-children dropMenu"><a href="#">Home page</a>';
        custommenuHTML +=                                        '<ul class="sub-menu">';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children dropMenu"><a href="#">Layout Style</a>';
        custommenuHTML +=                                                '<ul class="sub-menu">';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">One page</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Online Store</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Product Lounch</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Portfolio</a></li>';
        custommenuHTML +=                                                '</ul>';
        custommenuHTML +=                                            '</li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children dropMenu"><a href="#">Topic Style</a>';
        custommenuHTML +=                                                '<ul class="sub-menu">';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Landing</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Corporate</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Design Agency</a></li>';
        custommenuHTML +=                                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Blog Style</a></li>';
        custommenuHTML +=                                                '</ul>';
        custommenuHTML +=                                            '</li>';
        custommenuHTML +=                                        '</ul>';
        custommenuHTML +=                                    '</li>';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Shop</a></li>';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-taxonomy menu-item-object-category"><a href="#">Blog</a></li>';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-taxonomy menu-item-object-category"><a href="#">Portfolio</a></li>';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children dropMenu"><a href="#">Features</a>';
        custommenuHTML +=                                        '<ul class="sub-menu">';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">About Us</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Our team</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Price Table</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">FAQ’s</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Services</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Contacts</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Page 404</a></li>';
        custommenuHTML +=                                            '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Typography</a></li>';
        custommenuHTML +=                                        '</ul>';
        custommenuHTML +=                                    '</li>';
        custommenuHTML +=                                    '<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="#">Shortcodes</a></li>';
        custommenuHTML +=                                '</ul>';
        custommenuHTML +=                            '</nav>';
        custommenuHTML +=                            '<div class="searchBlock">';
        custommenuHTML +=                                '<form role="search" method="get" class="search-form" action="#">';
        custommenuHTML +=                                    '<input type="text" class="searchField" placeholder="Search" value="" name="s" title="Search for:">';
        custommenuHTML +=                                    '<button type="submit" class="searchSubmit"></button>';
        custommenuHTML +=                                '</form>';
        custommenuHTML +=                            '</div>';
        custommenuHTML +=                        '</div>';
        custommenuHTML +=                    '</div>';
        custommenuHTML +=                '</div>';
        custommenuHTML +=            '</div>';
        custommenuHTML +=            '<div id="tabsFavorite" class="tab-pane fade tabsMenuBody ui-tabs-panel ui-widget-content ui-corner-bottom" >';
        custommenuHTML +=                '<div class="addBookmarkArea"><a href="#" class="addBookmark">add bookmark</a></div>';
        custommenuHTML +=                '<div class="sc_scroll sc_scroll_vertical scroll-container scroll-no-swiping" id="bookmarks_scroll">';
        custommenuHTML +=                    '<div class="sc_scroll_wrapper">';
        custommenuHTML +=                        '<div class="sc_scroll_slide">';
        custommenuHTML +=                            '<ol class="listBookmarks ui-sortable"></ol>';
        custommenuHTML +=                        '</div>';
        custommenuHTML +=                    '</div>';
        custommenuHTML +=                    '<div id="bookmarks_scroll_bar" class="sc_scroll_bar sc_scroll_bar_vertical bookmarks_scroll_bar"></div>';
        custommenuHTML +=                '</div>';
        custommenuHTML +=            '</div>';
        custommenuHTML +=        '</div>';
        custommenuHTML +=    '</div>';
        custommenuHTML +='</div>';

        jQuery('body').append(custommenuHTML);
});