      var massagerHTML  = '<script type="text/javascript">';
      massagerHTML  +=   'THEMEREX_MESSAGE_BOOKMARK_ADD   = "Add the bookmark";';
      massagerHTML  +=   'THEMEREX_MESSAGE_BOOKMARK_ADDED = "Current page has been successfully added to the bookmarks. You can see it in the right panel on the tab \'Bookmarks\'";';
      massagerHTML  +=   'THEMEREX_MESSAGE_BOOKMARK_TITLE = "Enter bookmark title";';
      massagerHTML  +=   'THEMEREX_MESSAGE_BOOKMARK_EXISTS= "Current page already exists in the bookmarks list";';
      massagerHTML  +=   'THEMEREX_MESSAGE_SEARCH_ERROR = "Error occurs in AJAX search! Please, type your query and press search icon for the traditional search way.";';
      massagerHTML  +=   'THEMEREX_MESSAGE_EMAIL_CONFIRM= "On the e-mail address <b>%s</b> we sent a confirmation email.<br>Please, open it and click on the link.";';
      massagerHTML  +=   'THEMEREX_MESSAGE_EMAIL_ADDED  = "Your address <b>%s</b> has been successfully added to the subscription list";';
      massagerHTML  +=   'THEMEREX_REVIEWS_VOTE         = "Thanks for your vote! New average rating is:";';
      massagerHTML  +=   'THEMEREX_REVIEWS_ERROR        = "Error saving your vote! Please, try again later.";';
      massagerHTML  +=   'THEMEREX_MAGNIFIC_LOADING     = "Loading image #%curr% ...";';
      massagerHTML  +=   'THEMEREX_MAGNIFIC_ERROR       = "<a href=\"%url%\">The image #%curr%</a> could not be loaded.";';
      massagerHTML  +=   'THEMEREX_MESSAGE_ERROR_LIKE   = "Error saving your like! Please, try again later.";';
      massagerHTML  +=   'THEMEREX_GLOBAL_ERROR_TEXT    = "Global error text";';
      massagerHTML  +=   'THEMEREX_NAME_EMPTY           = "The name can\'t be empty";';
      massagerHTML  +=   'THEMEREX_NAME_LONG            = "Too long name";';
      massagerHTML  +=   'THEMEREX_EMAIL_EMPTY          = "Too short (or empty) email address";';
      massagerHTML  +=   'THEMEREX_EMAIL_LONG           = "Too long email address";';
      massagerHTML  +=   'THEMEREX_EMAIL_NOT_VALID      = "Invalid email address";';
      massagerHTML  +=   'THEMEREX_SUBJECT_EMPTY        = "The subject can\'t be empty";';
      massagerHTML  +=   'THEMEREX_SUBJECT_LONG         = "Too long subject";';
      massagerHTML  +=   'THEMEREX_MESSAGE_EMPTY        = "The message text can\'t be empty";';
      massagerHTML  +=   'THEMEREX_MESSAGE_LONG         = "Too long message text";';
      massagerHTML  +=   'THEMEREX_SEND_COMPLETE        = "Send message complete!";';
      massagerHTML  +=   'THEMEREX_SEND_ORDER_COMPLETE  = "Thank you! We\'ll be in touch.";';
      massagerHTML  +=   'THEMEREX_SEND_ERROR           = "Transmit failed!";';
      massagerHTML  +=   'THEMEREX_LOGIN_EMPTY          = "The Login field can\'t be empty";';
      massagerHTML  +=   'THEMEREX_LOGIN_LONG           = "Too long login field";';
      massagerHTML  +=   'THEMEREX_PASSWORD_EMPTY       = "The password can\'t be empty and shorter then 5 characters";';
      massagerHTML  +=   'THEMEREX_PASSWORD_LONG        = "Too long password";';
      massagerHTML  +=   'THEMEREX_PASSWORD_NOT_EQUAL   = "The passwords in both fields are not equal";';
      massagerHTML  +=   'THEMEREX_REGISTRATION_SUCCESS = "Registration success! Please log in!";';
      massagerHTML  +=   'THEMEREX_REGISTRATION_FAILED  = "Registration failed!";';
      massagerHTML  +=   'THEMEREX_REGISTRATION_AUTHOR  = "Your account is waiting for the site admin moderation!";';
      massagerHTML  +=   'THEMEREX_GEOCODE_ERROR        = "Geocode was not successful for the following reason:";';
      massagerHTML  +=   'THEMEREX_GOOGLE_MAP_NOT_AVAIL = "Google map API not available!";';
      massagerHTML  +='</script>';

            jQuery('body').append(massagerHTML);
