var swpRightHTML  ='<div class="swpRightPos">';
swpRightHTML  +=    '<a href="#" class="swpRightPosButton">';
swpRightHTML  +=        '<span class="rt-icon-cog2 animate-spin"></span>';
swpRightHTML  +=    '</a>';
swpRightHTML  +=    '<div>';
swpRightHTML  +=        '<ul class="nav nav-tabs tabsMenuHead" role="tablist">';
swpRightHTML  +=            '<li class="active" role="tab" data-toggle="tab">';
swpRightHTML  +=                '<a class="tabsCustom" href="#tabsCustom" role="tab" data-toggle="tab"></a>';
swpRightHTML  +=            '</li>';
swpRightHTML  +=            '<li class="">';
swpRightHTML  +=                '<a class="tabsMenu" href="#tabsMenu" role="tab" data-toggle="tab"></a>';
swpRightHTML  +=            '</li>';
swpRightHTML  +=            '<li class="">';
swpRightHTML  +=                '<a class="tabsFavorite" href="#tabsFavorite" role="tab" data-toggle="tab"></a>';
swpRightHTML  +=            '</li>';
swpRightHTML  +=        '</ul>';
swpRightHTML  +=        '<div class="tab-content">';
swpRightHTML  +=            '<div id="tabsCustom" class="tab-pane fade in active tabsMenuBody" >';
swpRightHTML  +=                '<div id="custom_options">';
swpRightHTML  +=                    '<div id="custom_options_scroll" class="sc_scroll scroll-container inited custom_options_scroll">';
swpRightHTML  +=                        '<div class="sc_scroll_wrapper">';
swpRightHTML  +=                            '<div class="sc_scroll_slide">';
swpRightHTML  +=                                '<div class="co_header">';
swpRightHTML  +=                                    '<h4 class="co_title">Choose Your Style</h4>';
swpRightHTML  +=                                    '<a href="" class="co_reset_to_default fa fa-refresh" title="Reset to default"></a>';
swpRightHTML  +=                                '</div>';
swpRightHTML  +=                                '<div class="co_options">';
swpRightHTML  +=                                    '<form name="co_form">';
swpRightHTML  +=                                        '<input type="hidden" id="co_site_url" name="co_site_url" value="#">';
swpRightHTML  +=                                        '<div class="co_form_row">';
swpRightHTML  +=                                            '<input type="hidden" name="co_body_style" value="fullscreen">';
swpRightHTML  +=                                            '<span class="co_label">Body style:</span>';
swpRightHTML  +=                                            '<div class="co_switch_box">';
swpRightHTML  +=                                                '<a href="#" class="co_switch_label wide">Wide</a>';
swpRightHTML  +=                                                '<div class="switcher"><a href="#"></a></div>';
swpRightHTML  +=                                                '<a href="#" class="co_switch_label boxed">Boxed</a>';
swpRightHTML  +=                                            '</div>';
swpRightHTML  +=                                        '</div>';
swpRightHTML  +=                                        '<div class="co_form_row">';
swpRightHTML  +=                                            '<span class="co_label">Theme colors:</span>';
swpRightHTML  +=                                            '<div class="co_form_subrow">';
swpRightHTML  +=                                                '<input type="hidden" name="co_theme_color" value="#f55858">';
swpRightHTML  +=                                                '<div id="co_theme_color" class="iColorPicker"></div>';
swpRightHTML  +=                                                '<input type="hidden" name="co_theme_color_1" value="#ffc455">';
swpRightHTML  +=                                                '<div id="co_theme_color_1" class="iColorPicker"></div>';
swpRightHTML  +=                                                '<input type="hidden" name="co_theme_color_2" value="#392071">';
swpRightHTML  +=                                                '<div id="co_theme_color_2" class="iColorPicker"></div>';
swpRightHTML  +=                                                '<input type="hidden" name="co_theme_color_3" value="#05d1d4">';
swpRightHTML  +=                                                '<div id="co_theme_color_3" class="iColorPicker"></div>';
swpRightHTML  +=                                            '</div>';
swpRightHTML  +=                                        '</div>';
swpRightHTML  +=                                        '<div class="co_form_row">';
swpRightHTML  +=                                            '<input type="hidden" name="co_bg_pattern" value="">';
swpRightHTML  +=                                            '<span class="co_label">Theme pattern:</span>';
swpRightHTML  +=                                            '<div id="co_bg_pattern_list">';
swpRightHTML  +=                                                '<a href="#" id="pattern_1" class="co_pattern_wrapper"><img src="img/pattern_1_thumb2.png" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="pattern_2" class="co_pattern_wrapper"><img src="img/pattern_2_thumb2.png" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="pattern_3" class="no_margin co_pattern_wrapper"><img src="img/pattern_3_thumb2.png" alt=""></a>';
swpRightHTML  +=                                            '</div>';
swpRightHTML  +=                                        '</div>';
swpRightHTML  +=                                        '<div class="co_form_row">';
swpRightHTML  +=                                            '<input type="hidden" name="co_bg_image" value="">';
swpRightHTML  +=                                            '<span class="co_label">Backgroud images:</span>';
swpRightHTML  +=                                            '<div id="co_bg_images_list">';
swpRightHTML  +=                                                '<a href="#" id="image_1" class="co_image_wrapper"><img src="img/image_1_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="image_2" class="co_image_wrapper"><img src="img/image_2_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="image_3" class="no_margin co_image_wrapper"><img src="img/image_3_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="image_4" class="co_image_wrapper"><img src="img/image_4_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="image_5" class="co_image_wrapper"><img src="img/image_5_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                                '<a href="#" id="image_6" class="no_margin co_image_wrapper"><img src="img/image_6_thumb2.jpg" alt=""></a>';
swpRightHTML  +=                                            '</div>';
swpRightHTML  +=                                            '<div id="co_bg_images"></div>';
swpRightHTML  +=                                        '</div>';
swpRightHTML  +=                                    '</form>';
swpRightHTML  +=                                '</div>';
swpRightHTML  +=                            '</div>';
swpRightHTML  +=                        '</div>';
swpRightHTML  +=                    '</div>';
swpRightHTML  +=                '</div>';
swpRightHTML  +=            '</div>';
swpRightHTML  +=            '<div id="tabsMenu" class="tab-pane fade tabsMenuBody" >';
swpRightHTML  +=                '<div class="sc_scroll sc_scroll_vertical scroll-container" id="panelmenu_scroll">';
swpRightHTML  +=                    '<div class="sc_scroll_wrapper">';
swpRightHTML  +=                        '<div class="sc_scroll_slide">';
swpRightHTML  +=                            '<nav role="navigation" class="panelmenu_area widget_area">';
swpRightHTML  +=                                '<ul id="panelmenu" class="">';
swpRightHTML  +=                                    '<li class="menu-item-has-children dropMenu"><a href="#">Home page</a>';
swpRightHTML  +=                                        '<ul class="sub-menu">';
swpRightHTML  +=                                            '<li class="menu-item-has-children dropMenu"><a href="#">Layout Style</a>';
swpRightHTML  +=                                                '<ul class="sub-menu">';
swpRightHTML  +=                                                    '<li ><a href="one-page.html">One page</a></li>';
swpRightHTML  +=                                                    '<li ><a href="store.html">Online Store</a></li>';
swpRightHTML  +=                                                    '<li ><a href="product-lounch.html">Product Lounch</a></li>';
swpRightHTML  +=                                                    '<li ><a href="portfolio.html">Portfolio</a></li>';
swpRightHTML  +=                                                '</ul>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li class="menu-item-has-children dropMenu"><a href="#">Topic Style</a>';
swpRightHTML  +=                                                '<ul class="sub-menu">';
swpRightHTML  +=                                                    '<li ><a href="landing.html">Landing</a></li>';
swpRightHTML  +=                                                    '<li ><a href="corporate.html">Corporate</a></li>';
swpRightHTML  +=                                                    '<li ><a href="design-agency.html">Design Agency</a></li>';
swpRightHTML  +=                                                    '<li ><a href="blog.html">Blog Style</a></li>';
swpRightHTML  +=                                                '</ul>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                        '</ul>';
swpRightHTML  +=                                    '</li>';
swpRightHTML  +=                                    '<li><a href="store.html">Shop</a></li>';
swpRightHTML  +=                                    '<li><a href="blog.html">Blog</a></li>';
swpRightHTML  +=                                    '<li><a href="portfolio.html">Portfolio</a></li>';
swpRightHTML  +=                                    '<li class="menu-item-has-children dropMenu"><a href="#">Features</a>';
swpRightHTML  +=                                        '<ul class="sub-menu">';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="about-us.html">About Us</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="our-team.html">Our team</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="price-table.html">Price Table</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="faqs.html">FAQ’s</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="services.html">Services</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="contacts.html">Contacts</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="not-existing-page.html">Page 404</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                            '<li>';
swpRightHTML  +=                                                '<a href="typography.html">Typography</a>';
swpRightHTML  +=                                            '</li>';
swpRightHTML  +=                                        '</ul>';
swpRightHTML  +=                                    '</li>';
swpRightHTML  +=                                    '<li ><a href="shortcodes.html">Shortcodes</a></li>';
swpRightHTML  +=                                '</ul>                       ';
swpRightHTML  +=                            '</nav>';
swpRightHTML  +=                            '<div class="searchBlock">';
swpRightHTML  +=                                '<form role="search" method="get" class="search-form" action="#">';
swpRightHTML  +=                                    '<input type="text" class="searchField" placeholder="Search" value="" name="s" title="Search for:">';
swpRightHTML  +=                                    '<button type="submit" class="searchSubmit"></button>';
swpRightHTML  +=                                '</form>';
swpRightHTML  +=                            '</div>';
swpRightHTML  +=                        '</div>';
swpRightHTML  +=                    '</div>';
swpRightHTML  +=                '</div>';
swpRightHTML  +=            '</div>';
swpRightHTML  +=            '<div id="tabsFavorite" class="tab-pane fade tabsMenuBody" >';
swpRightHTML  +=                '<div class="addBookmarkArea">';
swpRightHTML  +=                    '<a href="#" class="addBookmark">add bookmark</a>';
swpRightHTML  +=                '</div>';
swpRightHTML  +=                '<div class="sc_scroll sc_scroll_vertical scroll-container scroll-no-swiping" id="bookmarks_scroll">';
swpRightHTML  +=                    '<div class="sc_scroll_wrapper">';
swpRightHTML  +=                        '<div class="sc_scroll_slide">';
swpRightHTML  +=                            '<ol class="listBookmarks ui-sortable"></ol>';
swpRightHTML  +=                        '</div>';
swpRightHTML  +=                    '</div>';
swpRightHTML  +=                    '<div id="bookmarks_scroll_bar" class="sc_scroll_bar sc_scroll_bar_vertical bookmarks_scroll_bar"></div>';
swpRightHTML  +=                '</div>';
swpRightHTML  +=            '</div>';
swpRightHTML  +=        '</div>';
swpRightHTML  +=    '</div>';
swpRightHTML  +='</div>';
      
jQuery('body').append(swpRightHTML);

$(window).load(function(){
    $(".swpRightPos .tab-content .sc_scroll").mCustomScrollbar();
    theme:"dark"
}); 
